//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QuestDesigner.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MDICHILD                    129
#define IDI_BEGIN                       130
#define IDR_MDISCRIPTED                 130
#define IDI_DOC_SCRIPT                  130
#define IDR_MDIMAPED                    131
#define IDI_DOC_MAP                     131
#define IDR_MDIWORLDED                  132
#define IDI_DOC_WORLD                   132
#define IDR_MDISPTSHTED                 133
#define IDI_DOC_SPRITE                  133
#define IDI_DOC_SPTSHT                  134
#define IDI_DOC_WAV                     135
#define IDI_DOC_MIDI                    136
#define IDI_FOLDER_PROJECT              137
#define IDI_FOLDER_CLOSED               138
#define IDI_FOLDER_OPEN                 139
#define IDI_FOLDER_LIB                  140
#define IDI_END                         140
#define ID_POSITION_PANE                150
#define ID_OVERTYPE_PANE                151
#define ID_READONLY_PANE                152
#define ID_ICON_PANE                    153
#define IDB_TAB_ICONS                   207
#define IDI_ICO_WARNING                 209
#define IDI_ICO_QUESTION                210
#define IDI_ICO_ERROR                   211
#define IDI_ICO_OK                      212
#define IDR_TB_SCRIPTED                 214
#define IDR_TB_MAPED_OBJECT             215
#define IDR_TB_FOLDERS                  216
#define IDR_TB_PROPVIEW                 217
#define IDC_ARROWADD                    224
#define IDC_ARROWDEL                    225
#define IDC_ARROWADD1                   226
#define IDC_ARROWSELECT                 226
#define IDR_TB_MAPED_MAIN               227
#define IDR_TB_MAPED_BASIC              228
#define IDD_PROPERTIES                  230
#define IDD_PROPERTIES_NOTIMPLEMENTED   231
#define IDD_PROPERTIESVIEW              231
#define ID_FILE_PREFERENCES             232
#define ID_CLOSE                        240
#define ID_CLOSE_ACA                    241
#define IDB_DRAGIMG                     243
#define IDD_PROPERTYVIEW                244
#define ID_VIEW_OTHERWINDOWS            245
#define ID_VIEW_PANEFIRST               500
#define ID_PANE_THINGSTODO              500
#define ID_PANE_PROJECTDESCRIPTION      501
#define ID_PANE_OUTPUTWINDOW            502
#define ID_PANE_PROPERTIES              503
#define ID_PANE_PROJECTEXPLORER         504
#define ID_PANE_QUESTEXPLORER           505
#define ID_PANE_SPRITESETEXPLORER       506
#define ID_VIEW_PANELAST                506
#define IDC_COMBO                       1000
#define IDC_LIST                        1001
#define IDC_TITLE                       1002
#define IDC_FRAME                       1003
#define IDC_DESCRIPTION                 1004
#define ID_APP_BUILD                    32770
#define ID_APP_CLOSE                    32771
#define ID_APP_HELP                     32772
#define ID_APP_MAPED                    32774
#define ID_APP_NEW                      32775
#define ID_APP_OPEN                     32776
#define ID_APP_SAVE                     32778
#define ID_APP_SPTSHTED                 32779
#define ID_APP_STATUS_BAR               32780
#define ID_APP_STOPBUILD                32781
#define ID_APP_TOOLBAR                  32782
#define ID_APP_WORLDED                  32783
#define ID_MAPED_ALBOTTOM               32784
#define ID_MAPED_ALCX                   32785
#define ID_MAPED_ALCY                   32786
#define ID_MAPED_ALLEFT                 32787
#define ID_MAPED_ALRIGHT                32788
#define ID_MAPED_ALTOP                  32789
#define ID_MAPED_ARROW                  32790
#define ID_MAPED_BOUNDS                 32791
#define ID_MAPED_C90                    32792
#define ID_MAPED_CC90                   32793
#define ID_MAPED_EQSIZE                 32797
#define ID_MAPED_EQXSIZE                32798
#define ID_MAPED_EQYSIZE                32799
#define ID_MAPED_FLIP                   32801
#define ID_MAPED_GRID                   32802
#define ID_MAPED_GRIDSNAP               32803
#define ID_MAPED_MIRROR                 32804
#define ID_MAPED_NOZOOM                 32805
#define ID_MAPED_OBJDWN                 32806
#define ID_MAPED_OBJUP                  32807
#define ID_MAPED_RULE                   32810
#define ID_MAPED_SELECT                 32811
#define ID_MAPED_SELECT_ALL             32812
#define ID_MAPED_SELECT_NONE            32813
#define ID_MAPED_TOBOTTOM               32814
#define ID_MAPED_TOTOP                  32815
#define ID_MAPED_ZOOMIN                 32817
#define ID_MAPED_ZOOMOUT                32818
#define ID_SCRIPTED_CLEAR_ALL_BOOKMARKS 32819
#define ID_SCRIPTED_CLOSE               32820
#define ID_COPY                         32821
#define ID_CUT                          32822
#define ID_ERASE                        32823
#define ID_SCRIPTED_FIND_NEXT           32824
#define ID_SCRIPTED_FIND_PREV           32825
#define ID_SCRIPTED_FIND_SELECTION      32826
#define ID_SCRIPTED_GOTO_LINE           32827
#define ID_SCRIPTED_GOTO_NEXT_BOOKMARK  32828
#define ID_SCRIPTED_GOTO_PREV_BOOKMARK  32829
#define ID_SCRIPTED_LOWERCASE           32830
#define ID_SCRIPTED_MATCH_BRACE         32831
#define ID_WORLDED_NEW                  32832
#define ID_SCRIPTED_NEW                 32832
#define ID_MAPED_OPEN                   32833
#define ID_WORLDED_OPEN                 32833
#define ID_SCRIPTED_OPEN                32833
#define ID_SCRIPTED_PAGE_SETUP          32834
#define ID_PASTE                        32835
#define ID_MAPED_PRINT                  32836
#define ID_WORLDED_PRINT                32836
#define ID_SCRIPTED_PRINT               32836
#define ID_SCRIPTED_PRINT_PREVIEW       32837
#define ID_MAPED_PRINT_SETUP            32838
#define ID_WORLDED_PRINT_SETUP          32838
#define ID_SCRIPTED_PRINT_SETUP         32838
#define ID_SCRIPTED_READ_ONLY           32839
#define ID_REDO                         32840
#define ID_MAPED_RELOAD                 32841
#define ID_WORLDED_RELOAD               32841
#define ID_SCRIPTED_RELOAD              32841
#define ID_MAPED_SAVE                   32842
#define ID_WORLDED_SAVE                 32842
#define ID_SCRIPTED_SAVE                32842
#define ID_MAPED_SAVE_ALL               32843
#define ID_WORLDED_SAVE_ALL             32843
#define ID_SCRIPTED_SAVE_ALL            32843
#define ID_WORLDED_SAVE_AS              32844
#define ID_SCRIPTED_SAVE_AS             32844
#define ID_SCRIPTED_SHOW_WHITE_SPACE    32845
#define ID_SCRIPTED_TAB                 32846
#define ID_SCRIPTED_TABIFY              32847
#define ID_SCRIPTED_TOGGLE_BOOKMARK     32848
#define ID_UNDO                         32849
#define ID_SCRIPTED_UNTAB               32850
#define ID_SCRIPTED_UNTABIFY            32851
#define ID_SCRIPTED_UPPERCASE           32852
#define ID_SCRIPTED_SELECT_ALL          32853
#define ID_SCRIPTED_FIND                32854
#define ID_SCRIPTED_REPLACE             32855
#define ID_SCRIPTED_CLEAR_ALL           32856
#define ID_SCRIPTED_REPEAT              32857
#define ID_MAPED_NEW                    32875
#define ID_MAPED_PLAYER                 32879
#define IDC_STATIC_CONFIGURE            32880
#define IDC_STATIC_OPTION               32881
#define IDC_STATIC_INFO                 32882
#define IDC_PROPERTIES_PLACEHOLDER      32883
#define IDC_PROPERTIES_TREE             32884
#define ID_APP_CONFIG                   32885
#define ID_MAPED_MASK                   32888
#define ID_MAPED_LAYER                  32889
#define ID_APP_SAVEALL                  32896
#define ID_APP_PRINT                    32897
#define ID_BUTTON32898                  32898
#define ID_PROJECT_OPEN                 32898
#define ID_FOLDERS_PROPERTIES           33000
#define ID_PROP_CAT                     33001
#define ID_PROP_SORT                    33002
#define ID_PROP_PROPERTIES              33003
#define ID_PROP_PAGES                   33004
#define IDS_MESSAGE_PASSED_N_OF_FILE    60001
#define IDS_WARNING_RELOAD              60002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        253
#define _APS_NEXT_COMMAND_VALUE         32899
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
