//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QuestDesigner.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PROPERTIES                  101
#define IDD_PROPERTIES_NOTIMPLEMENTED   102
#define IDD_PROPERTYVIEW                103
#define IDR_MAINFRAME                   130
#define IDR_MDICHILD                    131
#define ID_POSITION_PANE                150
#define ID_OVERTYPE_PANE                151
#define ID_READONLY_PANE                152
#define ID_ICON_PANE                    153
#define IDR_TB_MAIN                     201
#define IDR_TB_MAPED_BASIC              202
#define IDR_TB_MAPED_OBJECT             203
#define IDR_TB_FOLDERS                  204
#define IDR_TB_PROPVIEW                 205
#define IDR_TB1_PROJECT                 210
#define IDR_TB1_MAIN                    211
#define IDR_TB1_MAPED_BASIC             212
#define IDR_TB1_MAPED_OBJECT            213
#define IDR_TB1_FOLDERS                 214
#define IDR_TB1_PROPVIEW                215
#define IDR_TB2_PROJECT                 220
#define IDR_TB2_MAIN                    221
#define IDR_TB2_MAPED_BASIC             222
#define IDR_TB2_MAPED_OBJECT            223
#define IDR_TB2_FOLDERS                 224
#define IDR_TB2_PROPVIEW                225
#define IDR_TB3_PROJECT                 230
#define IDR_TB3_MAIN                    231
#define IDR_TB3_MAPED_BASIC             232
#define IDR_TB3_MAPED_OBJECT            233
#define IDR_TB3_FOLDERS                 234
#define IDR_TB3_PROPVIEW                235
#define IDI_ICO_WARNING                 240
#define IDI_ICO_QUESTION                241
#define IDI_ICO_ERROR                   242
#define IDI_ICO_OK                      243
#define IDB_DRAGIMG                     250
#define IDB_TAB_ICONS                   251
#define IDI_BEGIN                       260
#define IDI_DOC_UNKNOWN                 260
#define IDR_MDISCRIPTED                 261
#define IDI_DOC_SCRIPT                  261
#define IDR_MDIMAPED                    262
#define IDI_DOC_MAP                     262
#define IDR_MDIWORLDED                  263
#define IDI_DOC_WORLD                   263
#define IDR_PNG1                        263
#define IDR_MDISPTSHTED                 264
#define IDI_DOC_SPRITE                  264
#define IDI_DOC_SPTSHT                  265
#define IDI_DOC_SPTSET                  266
#define IDI_DOC_WAV                     267
#define IDI_DOC_MIDI                    268
#define IDI_FOLDER_PROJECT              269
#define IDI_FOLDER_CLOSED               270
#define IDI_FOLDER_OPEN                 271
#define IDI_FOLDER_LIB                  272
#define IDI_END                         272
#define IDD_ACK                         282
#define IDI_ICON1                       286
#define IDB_LOGO                        287
#define IDB_COMBO_ICONS                 293
#define IDB_COMBO_ICONS2                294
#define ID_VIEW_PANEFIRST               500
#define ID_PANE_THINGSTODO              500
#define ID_PANE_PROJECTDESCRIPTION      501
#define ID_PANE_OUTPUTWINDOW            502
#define ID_PANE_PROPERTIES              503
#define ID_PANE_PROJECTEXPLORER         504
#define ID_PANE_QUESTEXPLORER           505
#define ID_PANE_SPRITESETEXPLORER       506
#define ID_VIEW_PANELAST                506
#define IDC_ARROWADD                    1000
#define IDC_ARROWDEL                    1001
#define IDC_ARROWSELECT                 1002
#define IDC_COMBO                       1003
#define IDC_LIST                        1004
#define IDC_TITLE                       1005
#define IDC_FRAME                       1006
#define IDC_DESCRIPTION                 1007
#define IDC_MHAND                       1008
#define IDC_PROPERTIES_PLACEHOLDER      1009
#define IDC_PROPERTIES_TREE             1010
#define IDC_STATIC_CONFIGURE            1011
#define IDC_STATIC_INFO                 1012
#define IDC_STATIC_OPTION               1013
#define IDC_GPL_EDIT                    1020
#define IDC_EMAIL1_STATIC               1021
#define IDC_URL1_STATIC                 1022
#define IDC_ACK_BUTTON                  1023
#define IDC_THANKS_EDIT                 1024
#define ID_PROJECT_OPEN                 32000
#define ID_FOLDERS_PROPERTIES           32001
#define ID_PROP_CAT                     32002
#define ID_PROP_PAGES                   32003
#define ID_PROP_PROPERTIES              32004
#define ID_PROP_SORT                    32005
#define ID_APP_BUILD                    32200
#define ID_APP_CLOSE                    32201
#define ID_APP_HELP                     32202
#define ID_APP_MAPED                    32203
#define ID_APP_NEW                      32204
#define ID_APP_OPEN                     32205
#define ID_APP_PREFERENCES              32206
#define ID_APP_PRINT                    32207
#define ID_APP_PRINT_SETUP              32208
#define ID_APP_PRINT_PREVIEW            32209
#define ID_APP_SAVE_ALL                 32210
#define ID_APP_SCRIPTED                 32211
#define ID_APP_SPTSHTED                 32212
#define ID_APP_STATUS_BAR               32213
#define ID_APP_STOPBUILD                32214
#define ID_APP_TOOLBAR                  32215
#define ID_APP_WORLDED                  32216
#define ID_APP_RELOAD                   32217
#define ID_MAPED_ALBOTTOM               32250
#define ID_MAPED_ALCX                   32251
#define ID_MAPED_ALCY                   32252
#define ID_MAPED_ALLEFT                 32253
#define ID_MAPED_ALRIGHT                32254
#define ID_MAPED_ALTOP                  32255
#define ID_MAPED_ARROW                  32256
#define ID_MAPED_BOUNDS                 32257
#define ID_MAPED_C90                    32258
#define ID_MAPED_CC90                   32259
#define ID_MAPED_EQSIZE                 32260
#define ID_MAPED_EQXSIZE                32261
#define ID_MAPED_EQYSIZE                32262
#define ID_MAPED_FLIP                   32263
#define ID_MAPED_GRID                   32264
#define ID_MAPED_GRIDSNAP               32265
#define ID_MAPED_LAYER                  32266
#define ID_MAPED_MASK                   32267
#define ID_MAPED_MIRROR                 32268
#define ID_MAPED_NOZOOM                 32270
#define ID_MAPED_OBJDWN                 32271
#define ID_MAPED_OBJUP                  32272
#define ID_MAPED_PLAYER                 32273
#define ID_MAPED_RULE                   32274
#define ID_MAPED_SELECT                 32275
#define ID_MAPED_SELECT_ALL             32276
#define ID_MAPED_SELECT_NONE            32277
#define ID_MAPED_TOBOTTOM               32278
#define ID_MAPED_TOTOP                  32279
#define ID_MAPED_ZOOMIN                 32280
#define ID_MAPED_ZOOMOUT                32281
#define ID_SCRIPTED_CLEAR_ALL_BOOKMARKS 32301
#define ID_SCRIPTED_FIND_NEXT           32304
#define ID_SCRIPTED_FIND_PREV           32305
#define ID_SCRIPTED_FIND_SELECTION      32306
#define ID_SCRIPTED_GOTO_LINE           32307
#define ID_SCRIPTED_GOTO_NEXT_BOOKMARK  32308
#define ID_SCRIPTED_GOTO_PREV_BOOKMARK  32309
#define ID_SCRIPTED_LOWERCASE           32310
#define ID_SCRIPTED_MATCH_BRACE         32311
#define ID_SCRIPTED_READ_ONLY           32318
#define ID_SCRIPTED_SHOW_WHITE_SPACE    32326
#define ID_SCRIPTED_TAB                 32327
#define ID_SCRIPTED_TABIFY              32328
#define ID_SCRIPTED_TOGGLE_BOOKMARK     32329
#define ID_SCRIPTED_UNTAB               32330
#define ID_SCRIPTED_UNTABIFY            32331
#define ID_SCRIPTED_UPPERCASE           32332
#define ID_QUEST_OPEN                   32400
#define ID_QUEST_NEW                    32401
#define ID_SCRIPTED_CODELIST            32404
#define ID_SCRIPTED_CODETIP1            32405
#define ID_SCRIPTED_CODETIP2            32406
#define ID_APP_NOSOUND                  32408
#define ID_MAPED_SELHOLD                32410
#define ID_APP_SAVE                     57603
#define ID_APP_SAVE_AS                  57604
#define ID_ERASE                        57632
#define ID_SCRIPTED_CLEAR_ALL           57633
#define ID_COPY                         57634
#define ID_CUT                          57635
#define ID_SCRIPTED_FIND                57636
#define ID_PASTE                        57637
#define ID_SCRIPTED_REPEAT              57640
#define ID_SCRIPTED_REPLACE             57641
#define ID_SCRIPTED_SELECT_ALL          57642
#define ID_UNDO                         57643
#define ID_REDO                         57644
#define IDS_MESSAGE_PASSED_N_OF_FILE    60001
#define IDS_WARNING_RELOAD              60002
#define IDS_DESC_EMPTY                  60100
#define IDS_DESC_DESC                   60101
#define IDS_DESC_NAME                   60102
#define IDS_DESC_HEIGHT                 60103
#define IDS_DESC_WIDTH                  60104
#define IDS_DESC_ISFLIPPED              60105
#define IDS_DESC_ISMIRRORED             60106
#define IDS_DESC_X                      60107
#define IDS_DESC_Y                      60108
#define IDS_DESC_ROTATION               60109
#define IDS_DESC_LAYER                  60110
#define IDS_DESC_SUBLAYER               60111
#define IDS_DESC_SPRITESHEET            60112
#define IDS_DESC_ISVISIBLE              60113
#define IDS_DESC_VCHAIN                 60114
#define IDS_DESC_HCHAIN                 60115
#define IDS_DESC_ALPHA                  60116
#define IDS_DESC_LIGHTNESS              60117
#define IDS_DESC_RGBCOLOR               60118
#define IDS_DESC_RGBCOLORH              60119

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        264
#define _APS_NEXT_COMMAND_VALUE         32414
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
